### ISSUE TITLE
Login fails if user uses a certain password (character set?)

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#3] opened 2015-02-02 12:05 UTC
As reported by user `l*****`, when signing up with a specific password, logging in isn't possible.

The password in question:

    <redacted>

I could already reproduce the error.

Adding @zeisss to the discussion.

Original Author: @marian
Created at 05-01-2015 08:22:13
Gitlab: [giantswarm/cli!214](https://git.giantswarm.io/giantswarm/cli/issues/214)

**Comment by marians** [comment] 2015-11-24 08:33
@webwurst Have we seen this issue recently?

I think we could try to reproduce this with a worst case test string. Labelling backlog.

**Comment by webwurst** [comment] 2015-11-24 11:40
@marians I haven't seen this issue.

**Comment by marians** [comment] 2015-11-24 20:20
OK, in other words: @webwurst Have you recently heard of problems of this kind?

**Comment by webwurst** [comment] 2015-11-25 18:32
No sorry, I also didn't hear about something like this ;)

**Comment by marians** [comment] 2015-12-10 12:55
Closing this since no longer reproducible. Tracking related things in https://github.com/giantswarm/giantswarm/issues/393

**Closed by marians** 2015-12-10 12:55 UTC
Labels: 7 - status/pdv, kind/bug
