### ISSUE TITLE
If the swarm.json is not valid the CLI shouldn't panic

### ISSUE THREAD

**Issue by luebken** [giantswarm/cli#495] opened 2015-11-26 12:45 UTC
swarm.json

```
{
  "name": "httplog_service",
  "components": {
    "webserver": {
      "image": "luebken/httplog",
      "ports": 8000,
      "domains": {
        "80": "httplog.leaseweb-alpha.giantswarm.io/"
      }
    }
}
```

CLI command:

```
$ swarm create
Cannot create service due to a syntax error in 'swarm.json'.
panic: runtime error: index out of range

goroutine 1 [running]:
main.getLineContainingOffset(0x4cea10, 0xa, 0xd6, 0x0, 0x0, 0x0)
	/usr/code/utils.go:274 +0xfb
main.showSyntaxError(0x4cea10, 0xa, 0x22087a6060, 0x20885c230)
	/usr/code/utils.go:263 +0xaf
main.processCreate(0x4cea10, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x26b00)
	/usr/code/create.go:102 +0x610
main.createCmdRun(0x6eb700, 0x6fb580, 0x0, 0x0)
	/usr/code/create.go:66 +0x96
github.com/spf13/cobra.(*Command).execute(0x6eb700, 0x6fb580, 0x0, 0x0, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:530 +0x82f
github.com/spf13/cobra.(*Command).Execute(0x6ec6c0, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:613 +0x414
main.main()
	/usr/code/main.go:97 +0xbea

goroutine 5 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by marians** [comment] 2015-11-27 20:01
Just had this when trying to create a service using our `wordpress` test-app on aws-alpha.

The command executed: `swarm up swarm.json`

The CLI used was built from current branch `no-image-tag`.

Service definition:
```
{
  "name": "wordpress",
  "components": {
    "mysql": {
      "image": "mysql:5.5",
      "ports": 3306,
      "env": {
        "MYSQL_ROOT_PASSWORD": "mysecretpassword",
        "FOO": "bar"
      }
    },
    "wordpress": {
      "image": "wordpress:latest",
      "ports": 80,
      "env": {
        "WORDPRESS_DB_PASSWORD": "mysecretpassword"
      },
      "domains": {
        "80": "$GIANTSWARM_LOGIN_NAME-wordpress-test-app.alpha.private.giantswarm.io"
      },
      "links": [
        {
          "component": "mysql",
          "target_port": 3306
        }
      ]
    }
  }
}
```

```
Creating 'wordpress' in the 'marian/dev' environment…
Service created successfully!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2213d]

goroutine 1 [running]:
main.processUp(0x7fff5fbffb99, 0xa)
	/usr/code/up.go:96 +0x75d
main.upCmdRun(0x77da20, 0xc820157540, 0x1, 0x1)
	/usr/code/up.go:66 +0x59
github.com/spf13/cobra.(*Command).execute(0x77da20, 0xc8201574d0, 0x1, 0x1, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:530 +0x869
github.com/spf13/cobra.(*Command).Execute(0x77ca60, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:613 +0x46a
main.main()
	/usr/code/main.go:103 +0xc9c

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 33 [IO wait]:
net.runtime_pollWait(0x9eaea8, 0x72, 0xc8200101a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201c01b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201c01b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201c0150, 0xc8201d8000, 0x1000, 0x1000, 0x0, 0x9e5050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201c2010, 0xc8201d8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201be450, 0xa251b8, 0xc8201c2010, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201d2000, 0x5eda17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201d2000, 0xc8201d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xa65308, 0xc8201d2000, 0xc82013f0d8, 0xc8201d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82047f420, 0xc8201d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820324a20)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820324a20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82013f080)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc82013f080)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 53 [IO wait]:
net.runtime_pollWait(0x9ead28, 0x72, 0xc8200101a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820358b50, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820358b50, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820358af0, 0xc820100400, 0x400, 0x400, 0x0, 0x9e5050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c4d8, 0xc820100400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82040d200, 0xa251b8, 0xc82002c4d8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820343080, 0x5eda17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820343080, 0xc820433000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xa65308, 0xc820343080, 0xc82038ed68, 0xc820433000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204418a0, 0xc820433000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201e89c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201e89c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82038ed10)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc82038ed10)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by ewoutp** [comment] 2015-12-03 09:43
The issue reported by @marians above is already fixed with https://github.com/giantswarm/cli/commit/a7d6c4c4f61668510232efa68d40a340585d1303

**Comment by ewoutp** [comment] 2015-12-03 09:54
The issue reported by @luebken is no longer reproducable.
The output now is:

```
$ swarm up
Cannot parse service definition: unexpected end of JSON input
```

**Comment by ewoutp** [comment] 2015-12-03 10:09
Closing since the panic seems gone. If it re-appears, please create a new issue

**Closed by ewoutp** 2015-12-03 10:09 UTC
Labels: 4 - status/backlog, kind/bug
