### ISSUE TITLE
`swarm scaleup` on component without image results in `Wrong Input`

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#381] opened 2015-08-28 15:03 UTC
See summary and comment of https://github.com/giantswarm/app-service/pull/408

**Comment by zyndiecate** [comment] 2015-11-26 21:28
I cannot reproduce this issue. Who can? What to do? Closing?

```
$ cat swarm.pod.json
{
  "name": "pod",
  "components": {
    "root": {
      "pod": "children"
    },
    "root/a": {
      "image": "giantswarm/dummy-version:0.0.2"
    },
    "root/b": {
      "image": "giantswarm/dummy-version:0.0.2"
    }
  }
}
```

```
$ swarm --api-endpoint=http://192.168.33.101:8080/v1/ up swarm.pod.json
Creating 'pod' in the 'giantswarm/dev' environment…
Service created successfully!
Starting service 'pod'…
Waiting for 'pod' to get started…
Service 'pod' is up.
You can see all components using this command:

    swarm status pod

```

```
$ swarm --api-endpoint=http://192.168.33.101:8080/v1/ status pod
Service 'pod' is up

component  image                           instanceid    created              status
root/a     giantswarm/dummy-version:0.0.2  5idyibnm6vtm  2015-11-26 21:22:37  up
root/b     giantswarm/dummy-version:0.0.2  7zl1kkn9cuui  2015-11-26 21:22:37  up
```

```
$ swarm --api-endpoint=http://192.168.33.101:8080/v1/ scaleup root
Unknown component 'root'.
Please specify the component name in the format <service>/<component>.
See "swarm help scaleup" for details.
```

**Comment by ewoutp** [comment] 2015-11-27 06:43
It looks like the new implementation has fixed the issue, but introduced a new one.
IMO the "Unknown component" message is wrong. It is a known component, just one that you cannot invoke `scaleup` on.
Let's fix that

**Comment by zyndiecate** [comment] 2015-11-27 10:09
Mh, this is tricky. How to fix that? Based on the status output the component is unknown. Looks like we would need to introduce a new very specialized error. At the first glance I kind of dislike this.

**Comment by ewoutp** [comment] 2015-11-27 11:15
I still think we should be able to add some additional information to errors send from our backend.
So it is a "WrongInput" specialized as "cannot scale this component"

**Comment by zyndiecate** [comment] 2015-11-27 11:50
Then lets set the priority of this issue here lower and invest time to improve our error architecture/handling.

**Comment by ewoutp** [comment] 2015-11-27 12:26
+1

**Comment by marians** [comment] 2017-07-18 13:27
Closing, as we no longer maintain this CLI.

**Closed by marians** 2017-07-18 13:27 UTC
Labels: area/stability, kind/bug
